"""0001 initial schema

Revision ID: 5d46e445251c
Revises: 
Create Date: 2026-05-05 21:24:56.706974

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5d46e445251c'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=False)
        batch_op.create_index(
            batch_op.f('ix_customers_stripe_customer_id'),
            ['stripe_customer_id'],
            unique=True,
        )

    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('public_key_pem', sa.Text(), nullable=False),
    sa.Column('private_key_pem', sa.Text(), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('stripe_webhook_secret', sa.String(length=128), nullable=True),
    sa.Column('stripe_api_key', sa.String(length=128), nullable=True),
    sa.Column('jwt_issuer', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_slug'), ['slug'], unique=True)

    op.create_table('licenses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('licenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_licenses_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_licenses_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_licenses_product_id'), ['product_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('license_id', sa.String(length=36), nullable=True),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_license_id'), ['license_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_type'), ['type'], unique=False)

    op.create_table('installs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('license_id', sa.String(length=36), nullable=False),
    sa.Column('install_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('ip_addr_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('installs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installs_install_id'), ['install_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_installs_license_id'), ['license_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installs_license_id'))
        batch_op.drop_index(batch_op.f('ix_installs_install_id'))

    op.drop_table('installs')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_type'))
        batch_op.drop_index(batch_op.f('ix_events_product_id'))
        batch_op.drop_index(batch_op.f('ix_events_license_id'))
        batch_op.drop_index(batch_op.f('ix_events_created_at'))

    op.drop_table('events')
    with op.batch_alter_table('licenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_licenses_product_id'))
        batch_op.drop_index(batch_op.f('ix_licenses_key'))
        batch_op.drop_index(batch_op.f('ix_licenses_customer_id'))

    op.drop_table('licenses')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_slug'))

    op.drop_table('products')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_stripe_customer_id'))
        batch_op.drop_index(batch_op.f('ix_customers_email'))

    op.drop_table('customers')
    # ### end Alembic commands ###
