"""add license webhook_url + webhook_secret

Revision ID: 62011ea1b324
Revises: 5d46e445251c
Create Date: 2026-05-06 23:23:50.992918

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '62011ea1b324'
down_revision: str | Sequence[str] | None = '5d46e445251c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webhook_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('webhook_secret', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licenses', schema=None) as batch_op:
        batch_op.drop_column('webhook_secret')
        batch_op.drop_column('webhook_url')

    # ### end Alembic commands ###
